name: 🔌 Plugin | Package and release

on:
  push:
    tags:
      - '*'
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
#        with:
#          submodules: true

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Qt lrelease
        run: |
          sudo apt-get update
          sudo apt-get install qtbase5-dev qttools5-dev-tools

      - name: Install qgis-plugin-ci
        run: pip3 install qgis-plugin-ci

      - name: copy licence
        run: cp LICENSE swissgeodownloader/LICENSE

      - name: Package
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        run: |
          VERSION=0.0.0
          qgis-plugin-ci package ${VERSION}

      - uses: actions/upload-artifact@v4
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        with:
          name: swissgeodownloader_dev
          path: swissgeodownloader.0.0.0.zip
          if-no-files-found: error

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION=${{ github.ref_name }}
          qgis-plugin-ci release ${VERSION} \
            --github-token ${{ secrets.GITHUB_TOKEN }} \
            --osgeo-username ${{ secrets.OSGEO_USERNAME }} \
            --osgeo-password ${{ secrets.OSGEO_PASSWORD }}
